### ISSUE TITLE
Issue with active annotations depending on external model files

### ISSUE THREAD

**Issue by nils-christian** [eclipse/xtext-xtend#664] opened 2018-12-10 17:09 UTC
Hi,

I would like to thank you first for providing us with Xtend. We really appreciate the language and everything that comes with it.

Now about our issue. We encountered a problem with the active annotations. I try to simplify it as much as possible. We encountered it with Xtend 2.14, but I have the same issue with an Eclipse with 2.16.
* We have _ActiveAnnotation1_, which reads a model file (let's call it _File.txt_) located next to the annotated class. It generates a new annotation _GeneratedAnnotation_ (a simple Java annotation).
* We have another annotation _ActiveAnnotation2_, which reads this file as well and adds the generated annotation to the annotated class.

So far this works without any issues. When we change _File.txt_, everything is updated as expected. Now we want to use the same model file to generate some more elements in another project. It is not possible to put the model file somewhere else and reference it from another project. It seems that the active annotation can not "break out" from its project context using the _FileSystemSupport_ etc. We therefore use the elements, generated from _ActiveAnnotation1_ and _ActiveAnnotation2_ to generate further elements.

* We have _ActiveAnnotation3_ which gets a reference to the class annotated with _ActiveAnnotation2_. This annotation retrieves the given class and locates the _GeneratedAnnotation_ instance at this class. 

This is where our issue occurs. _ActiveAnnotation3_ cannot find _GeneratedAnnotation_. It can only find _ActiveAnnotation2_ and the suppress warnings annotation. If we perform a Maven install on the project in which the class annotated with _ActiveAnnotation2_ lies and close it, _ActiveAnnotation3_ can locate _GeneratedAnnotation_ as expected.

I created a simple project to demonstrate the issue: https://github.com/nils-christian/xtend-active-annotation-issue. It consists of four modules. Module a contains the first two active annotations. Module b uses these annotations and contains thus classes annotated with  _ActiveAnnotation1_ and _ActiveAnnotation2_. Module c contains _ActiveAnnotation3_ which only retrieves the given class, assembles a string from all annotations and writes it as warning to the annotated class. Module d finally contains the class annotated with _ActiveAnnotation3_. Note how it references the class annotated with _ActiveAnnotation2_. If you perform a Maven install and close Module b the annotation can be found again.

Can you help us here? We tried to debug the issue. It seems that _ActiveAnnotation2_ is called multiple times by Eclipse. If the context is in Module b it works, but then it is called again in the context of Module d and Eclipse no longer likes the path to the model file (because it is located in another project).

Best regards

  Nils Ehmke

**Comment by kthoms** [comment] 2018-12-11 08:14
Thank you Nils for the detailed report and the example project. This sounds like a corner case where I have doubts that we can invest enough time into ATM. Please bare with us if it will take a while until we can have a deeper look into it.
Is this a blocker for your project or can you work around?

**Comment by OLibutzki** [comment] 2018-12-11 08:33
Hi @kthoms,

we currently prepare a conference talk in January. In the first place it's a blocker for what we want to present there. In this context we just need a very simple generator. We currently investigate how to circumvent this issue with a Java main method (and exec-maven-plugin and m2e for IDE integration). That's not elegant, but might work for the moment.

Anyway, we are keen to support you as much as we can to fix this.

**Comment by cdietrich** [comment] 2018-12-11 08:35
@szarnekow do you have any idea?

**Comment by nils-christian** [comment] 2018-12-11 19:33
Hello @kthoms,

I expected this to be a corner case. However, I appreciate a fix or a suggestion for the issue. For the moment, as Oliver already told you, we will use a workaround for our generator.

Thank you very much and best regards

  Nils

**Comment by cdietrich** [comment] 2018-12-14 07:30
@nils-christian i tried to follow your description but could not really find out how to "reproduce" the problem

**Comment by cdietrich** [comment] 2018-12-14 08:07
there is a hidden java.lang.IllegalArgumentException: The file cannot be found: /xtend-issue-b/src/main/java/de/rhocas/b/File.txt

the problem is that 

org.eclipse.xtend.core.macro.AbstractFileSystemSupport.getPath(URI, URI, Path)

cannot deal with
- absoluteUri: platform:/resource/xtend-issue-b/src/main/java/de/rhocas/b/AnnotatedClass2.xtend
- baseUri: platform:/resource/xtend-issue-d/
- basePath: /xtend-issue-d

**Comment by cdietrich** [comment] 2018-12-14 08:10
=> basePath looks bogus to me.

**Comment by cdietrich** [comment] 2018-12-14 08:14
relates to https://github.com/eclipse/xtext-xtend/issues/383

**Comment by nils-christian** [comment] 2018-12-14 08:49
Hello @cdietrich,

Yes, this is exactly the problem. One would expect that ActiveAnnotation3 could detect also the newly generated annotation.

We also recognized the IllegalArgumentException and wondered that Eclipse "hides" this exception.

**Comment by cdietrich** [comment] 2023-04-17 08:54
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext

**Closed by cdietrich** 2023-04-17 08:54 UTC
