### ISSUE TITLE
Xtend sources not available in app launched from RCP app

### ISSUE THREAD

**Issue by andylowry** [eclipse/xtext-xtend#590] opened 2018-09-27 01:04 UTC
Hi. We have an RCP application that supports creation and launching of Java applications that may include Xtend sources. Everything works great except when it comes to debugging these apps. The debugger unable to find the xtend sources. The editor shows this:

![image](https://user-images.githubusercontent.com/108675/46117284-68c58900-c1ce-11e8-94b4-f0b452490a42.png)

No amount of attempting to configure the source lookup path seems to do the trick.

Probably related, we see a lot of these in the error view:

> org.eclipse.xtext.builder.smap.DerivedResourceMarkerCopier  - Failed to find Storage. Please make sure there are no outdated generated files. URI: platform:/resource/XX/home/andy/RepreZen/workspace/XX/src/main/java/com/example/xX/PerSchemaGenerator.xtend

The `platform:` URL starts out looking OK - `XX` is the name of the project this came from. But that's followed by the absolute path, in my host file system, to the project folder (`/home/andy/RepreZen/workspace/XX`) and then the rest of the resource path.

It seems likely that these mangled URLs are related to the source path failure.

Sample projects that fail in RCP work just fine in a basic Eclipse (Oxygen, in this case) installation.

So my question: is this something we've got screwed up in our RCP app, or is it an Xtext/Xtend bug? And if the latter, are there any suggestions for a possible work-around?

Xtext SDK v2.9.1 is included in the target platform of our RCP app. I've seen this behavior (including both the source path failure and the info messages in the error view) with projects configured for 2.9.1 and 2.15.0.

**Comment by andylowry** [comment] 2018-09-27 01:19
An additional, perhaps related symptom: When I right-click on an Xtend class with a `def public static void main(String[] args)` method, the **Run As** context menu for that class in project explorer does _not_ show **Java Application**, as it does for the derived class in the `xtend-gen` folder.

**Comment by kthoms** [comment] 2018-09-27 06:35
Indeed the absolute path is strange. `platform:/resource` should be followed by a project name. Since you likely will have bundled `PerSchemaGenerator.xtend` in your RCP app and won't be in the workspace, the URI seems wrong.

Haven't seen this kind of error before.

Note that you are on a pretty old version, latest is 2.15. You should try upgrading.

**Comment by cdietrich** [comment] 2018-09-27 06:51
Could you please provide a minimal reproducing example and steps

**Comment by andylowry** [comment] 2018-09-27 19:17
Many thanks... wishful thinking that someone might have a quick solution to recommend was, of course a long-shot. So now we'll get to the real work. :-)

I've managed to whittle our dozens-of-plugins product down to a handful of plugins, including our fairly complex  Xtext-based model and parser. The resulting product still exhibits the symptoms I mentioned above. Removing the model & parser makes the symptoms disappear.

So at this point we're going to do some more detailed debugging to try to get to the bottom of this. You'll hear from us, either when we have a resolution or if we run into questions.

In the meantime, thanks for the responses so far. Any further ideas or recommendations will be gratefully accepted.

**Comment by cdietrich** [comment] 2018-10-16 08:35
@andylowry do you have any new intelligence on this issue?

**Comment by kthoms** [comment] 2018-11-05 04:58
I'll close this one for now since we can't reproduce it. Feel free to reopen when you can provide reproduction steps for us.

**Closed by kthoms** 2018-11-05 04:58 UTC

**Comment by Zannith** [comment] 2018-12-04 21:14
I have run into this same issue simply by creating a basic dsl with xtext version 2.15.0 with web support. I create a Jetty Debug run configuration in the web build.gradle file and run it. If i put a breakpoint in a xtend file like `XtextServlet` I get that Source not found message and I cannot seem to get the lookup Path right
