### ISSUE TITLE
Add new Xtend editor quickfixes on *.xtend files

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext-xtend#1060] opened 2020-05-28 14:21 UTC
The Xtend IDE should provide the following quickfixes on `*.xtend` files:

- [#398023](https://bugs.eclipse.org/bugs/show_bug.cgi?id=398023) 
- [#412593](https://bugs.eclipse.org/bugs/show_bug.cgi?id=412593)
- [#454088](https://bugs.eclipse.org/bugs/show_bug.cgi?id=454088)

@loradd Would you like to take care of this issue?

**Comment by loradd** [comment] 2020-06-01 08:04
Yes, I can take care of this. Thanks!

**Comment by loradd** [comment] 2020-06-02 07:00
@miklossy it is not clear what is meant with constant in [#454088](https://bugs.eclipse.org/bugs/show_bug.cgi?id=454088), do we mean a final static instance member?

**Comment by miklossy** [comment] 2020-06-02 08:12
Yes

**Comment by miklossy** [comment] 2020-06-08 06:13
Currently, whenever the Xtend IDE recognizes that a method is missing, it offers a quickfix for creating the method:
![screenshot](https://user-images.githubusercontent.com/20393472/83997838-9aa95f80-a95f-11ea-8ff0-94728c2b3719.png)
It should be useful to offer an additional quickfix for creating a private method, in the example above there should be three quickfixes:

- Change to 'a'
- Create public method 'm'
- Create private method 'm'

@loradd Maybe you can fix this first.

**Comment by szarnekow** [comment] 2020-06-08 06:19
@miklossy This should be discussed. I don't want to have quickfixes for all permutations of modifiers.

**Comment by miklossy** [comment] 2020-06-08 06:33
@szarnekow I do not want to have quickfixes for all permutations of modifiers either. But creating a private method would be very useful, at least I would use that one more often than creating a public method. Currently I use the quickfix that creates a public method and have to modify that one to convert the created public method to private.

Let's see what others think about this.

**Comment by kthoms** [comment] 2020-06-08 07:18
Creating a private method sounds as a likely choice. If this would be added I would not change the text for creating a public method, though.

**Comment by miklossy** [comment] 2020-06-08 07:22
**Hint:** JDT offers a quickfix for creating a private method, but no quickfix to create a public one.
![screenshot2](https://user-images.githubusercontent.com/20393472/84002932-84a09c80-a969-11ea-8949-398242722e48.png)

**Comment by szarnekow** [comment] 2020-06-08 07:35
JDT uses placeholders in the proposed method.

**Comment by miklossy** [comment] 2020-06-08 07:54
@szarnekow It is true:
![screenshot3](https://user-images.githubusercontent.com/20393472/84005776-eebb4080-a96d-11ea-8b3a-9ecba91642ab.png)
Placeholders are nice to have, but I would be also fine with two different quickfixes.

**Comment by szarnekow** [comment] 2020-06-08 08:00
Please note that there already two quickfixes `Create method` and `Create extension method` (the latter only, if there is an explicit receiver).
That would make it four quickfixes `Create method`, `Create private method`, `Create extension method` and `Create private extension method`.
I would object this kind of change for usability reasons. If you use the quickfix to create a method, you have to navigate to that method to create the body anyways.

**Comment by miklossy** [comment] 2020-06-08 08:02
@szarnekow What about changing the already existing two quickfixes to create private methods instead of public ones?

**Comment by szarnekow** [comment] 2020-06-08 08:22
@miklossy In Xtend, methods are public by default. Why should the quickfix create a non-default method? What would be a reasonable explanation for that behavior?

**Comment by miklossy** [comment] 2020-06-08 09:12
I use Xtend mostly to define JUnit test cases. When following the TDD manner, it is a common way to create test helper methods in the test class using that quick fix. Since the test helper methods are usually private, it would be useful to be able to create private method stubs using a quicfix.

Maybe we can unify the `create method` and the `create extension method` quickfixes into a single `create method` quickfix, since they create the same method stubs.

@cdietrich : What do you think?

**Comment by loradd** [comment] 2020-06-09 18:12
@miklossy I am not able to reproduce issue [#412593]( https://bugs.eclipse.org/bugs/show_bug.cgi?id=412593). The quickfix proposal concerns static members, not instance members, as expected. Could it be that the issue has already been solved?

**Comment by miklossy** [comment] 2020-06-10 04:34
@loradd I can still reproduce the problem:
![screencast](https://user-images.githubusercontent.com/20393472/84227356-7b880a80-aae4-11ea-9198-1accdc2bbc30.gif)

**Comment by szarnekow** [comment] 2020-06-15 06:42
I reconsidered this. It would be ok for me if we offered `Create private method` and `Create private extension` along with the currently available quickfixes.

**Comment by miklossy** [comment] 2020-07-19 07:01
@loradd How is the progress here?

**Comment by loradd** [comment] 2020-07-19 14:35
@miklossy waiting for a second review on pull request #1068

**Comment by miklossy** [comment] 2020-07-19 15:00
@cdietrich @szarnekow @ArneDeutsch @kthoms Could please someone review the PR?

**Comment by cdietrich** [comment] 2020-08-21 06:16
@miklossy what is the state?

**Comment by cdietrich** [comment] 2020-08-24 09:22
Fixed in 2.23

**Closed** 2020-08-24 09:22 UTC
Labels: good first issue
