### ISSUE TITLE
[AA] A locally defined Xtend type cannot be referenced in an active annotation

### ISSUE THREAD

**Issue by kuniss** [eclipse/xtext-xtend#336] opened 2017-12-22 13:15 UTC
When using an active annotation which has parameters referencing Java types, those Java types cannot be resolved if they are locally defined. It does not matter, whether this are real Java or types generated from Xtend types.

However, Java types referenced from outside the project are resolved well.

Note: The active annotation itself is defined outside from the affected project and itself referenced. So, it is not a AA wrong usage issue. 
I assume and scoping issue.

An example may be found here: https://github.com/kuniss/xtend-issues/tree/master/xtend-issue-336-aa-loca-typeref

Eclipse is reporting an similar error like the following form a pure Gradle build:
```
Working Directory: C:\Users\denis.kuniss\Eclipse-Oyxygen-Workspace\xtend-issues
Gradle User Home: C:\Users\denis.kuniss\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 4.4
Java Home: C:\Program Files\Java\jdk1.8.0_45
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: :build

The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
:generateXtext
ERROR:Couldn't resolve feature MyLocalType (file:/C:/Users/denis.kuniss/Eclipse-Oyxygen-Workspace/xtend-issues/src/main/java/de/grammarcraft/xtend/issues/aatyperef/AAnnotatedType.xtend line : 12 column : 45)
 FAILED
```

**Comment by cdietrich** [comment] 2017-12-23 08:26
potential workaround `type=typeof(MyLocalType)` leads to follow up errors. am nut sure if this is caused by the processor code

**Comment by kuniss** [comment] 2018-01-02 15:02
I guess, `typeof()` returns `null` too. That's not expected by the processor code as it expects to be called only in case of type correctness.  If you insert a project external type, e.g. `typeof(String)`, it works again.

So, I still assume a type scoping error in the Xtend AA processing.

Could some one point me to the code such that I could take a look into?

**Comment by cdietrich** [comment] 2018-01-02 15:23
@szarnekow do you have any idea or hints where to look?

**Comment by szarnekow** [comment] 2018-01-02 19:29
I suspect that something in `ConstantExpressionsInterpreter.findTypeByName(EObject, String)` which is ultimately called from `XtendJvmModelInferrer.infer(EObject, IJvmDeclaredTypeAcceptor, boolean)`. Here we have a `preIndexingPhase` set to `false` which will trigger the annotation processors indexing and inference. During indexing, the proxies are resolved and the type MyLocalType is tried to be located, when the annotation itself is translated to the processors model. The eager transformation suffers from the fact, that `AbstractProjectAwareResourceDescriptionsProvider.getResourceDescriptions(ResourceSet)` filters project-locally defined types from the scope unnecessarily, since we are actually no longer in the indexing phase. So if we'd make the transformation of annotation values lazy, this could work. Certainly worth a try.

**Comment by ArneDeutsch** [comment] 2018-06-27 13:55
I have debugged this a bit. I do not understand your very last suggestion @szarnekow . I can see the following:

- XtendJvmModelInferrer line 185 starts indexing: `compilerPhases.setIndexing(xtendFile, true);`
- XtendJvmModelInferrer line 197 calls doRegisterGlobals from annotation processors: `annotationProcessor.indexingPhase(ctx, wrapper, CancelIndicator.NullImpl);`
- Inside the doRegisterGlobals of the annotation processor `FunctionUnitProcessor` line 119 the value of `outputPorts` is queried and translated (https://github.com/kuniss/XtendFlow/blob/master/FlowDesignInXtend-ActiveAnnotations/src/de/grammarcraft/xtend/flow/annotations/FunctionUnit.xtend). The class literal is needed there to register a new interface.

Because of the last point I see no way to make it in a lazy way ... the `doRegisterGlobals`  is called during indexing, where local classes are hidden. And because the value is needed immediatly, there is no oportunity to resolve it lazy ... or do I missunderstood you?

**Comment by szarnekow** [comment] 2018-06-27 14:18
> Inside the doRegisterGlobals of the annotation processor FunctionUnitProcessor line 119 the value of outputPorts is queried and translated 

If I understand the code correctly, this could be done lazily thus in the generation / validation phase it would resolve the arguments correctly.

**Comment by ArneDeutsch** [comment] 2018-06-28 14:12
Ah ... you are suggesting to fix it in user code, not in Xtext, right?

Actually I have not yet understand why exactly classes from the actual project are filtered during indexing phase. The code and the comments just state that they are filtered but are silent about the why: https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/xtext/AbstractProjectAwareResourceDescriptionsProvider.java

**Comment by kuniss** [comment] 2018-06-29 07:42
@szarnekow, @ArneDeutsch Is the Xtend compiler the user code here? Or is it the Xtend source code which uses the AA?

**Comment by kuniss** [comment] 2019-05-23 20:21
@szarnekow, that's the issue I was referring today evening in our discussion. :smile:  
Would be interested in getting this issue solved and if possible, help to solve it. If you have any idea how I could contribute and help, any hint is welcome.

**Comment by cdietrich** [comment] 2023-04-17 08:43
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext

**Closed by cdietrich** 2023-04-17 08:43 UTC

**Comment by kuniss** [comment] 2023-04-18 20:08
@cdietrich Why do you think, it make sense to reopen it at Xtext repo?

Is this repo going to be shut down?

**Comment by cdietrich** [comment] 2023-04-19 04:45
@kuniss yes all code is now in github.com/eclipse/xtext
i dont think we can work on it. so reopening the issue has limited sense
