### ISSUE TITLE
Pressing Ctrl while content assist is open selects one line

### ISSUE THREAD

**Issue by danielwinkels** [eclipse/xtext-xtend#1242] opened 2021-09-28 13:41 UTC
### Description
The Xtend-Editor selects one line in the active editor when you open the content assist by pressing ctrl+space.

### Reproduction
Open an Xtend-file in the Xtend-Editor. Go to a line within a block and press **ctrl+space** to open the content assist.
Release the keys and press **ctrl** again but on it's own. Eclipse will select one line downwoards from your current cursor position.

I could not reproduce the same behaviour in the JDT Java Editor.
![a8lG7R38ne](https://user-images.githubusercontent.com/871600/135097820-03ad629c-aa13-4f46-b27d-1bf8cce927b6.gif)

### Version:
Windows 10 21H1
Eclipse 20210612-2011
Xtext Complete SDK 2.25.0.v20210301-1429

P.S.: This is my first issue, so please tell me, what i could do better.

**Comment by kthoms** [comment] 2021-09-28 14:10
Sounds well described. Thanks for reporting it.

**Comment by miklossy** [comment] 2021-09-28 14:15
I can reproduce the issue while editing *.xtend, *.xtext and in *.mwe2 files

**Comment by cdietrich** [comment] 2021-09-28 14:20
i dont understand, doesnt crtl do a replace proposal.
we do it also in whitespace, jdt does not
thus this is imho a duplicate of https://github.com/eclipse/xtext/issues/2503

**Comment by cdietrich** [comment] 2021-09-28 14:26
Why you see the selection that the replacement proposal will replace

**Comment by cdietrich** [comment] 2021-09-28 14:27
If there are 10 we lines or spaces it should select them too

**Comment by danielwinkels** [comment] 2021-09-28 14:29
> 
> 
> If there are 10 we lines or spaces it should select them too

It does select multiple lines.

**Comment by danielwinkels** [comment] 2021-10-01 06:58
Is this code responsible for the replacement of text instead of just inserting at the caret position?

**Comment by cdietrich** [comment] 2021-10-01 07:02
yes if you hit Crtl you switch the mode. (in newest eclipse jdt has replace by default and switches to insert on crtl, in Xtext its still the old way)
xtext is also happy to do replace proposals on whitespace, this is what eclipse/xtext#2503 is about

**Comment by danielwinkels** [comment] 2021-10-01 14:41
Can I do anything to help fix this?

**Comment by cdietrich** [comment] 2021-10-01 14:55
i have no clue on how to proper fix this. i also have no idea how platform/jdt detect that they are in whitespace and dont create replacement proposal. i dont know what my fix proposal will break ...

**Comment by cdietrich** [comment] 2021-10-11 05:41
is there an agreement that this is a dupe of eclipse/xtext#2503 now?

**Comment by cdietrich** [comment] 2021-11-11 08:11
dupicate of eclipse/xtext#2503

**Closed by cdietrich** 2021-11-11 08:11 UTC
Labels: confirmed
