### ISSUE TITLE
Rendering error in documentation

### ISSUE THREAD

**Issue by olenz** [eclipse/xtext-xtend#104] opened 2016-12-21 10:18 UTC
The documentation seems to have some rendering problems with short pieces of code. Have a look at:
http://www.eclipse.org/xtend/documentation/203_xtend_expressions.html

What I see is this (confirmed for Chrome and Firefox):
![image](https://cloud.githubusercontent.com/assets/158440/21385555/3e1f263a-c76f-11e6-9864-6066174e5a44.png)

**Comment by cdietrich** [comment] 2017-01-13 12:41
Duplicate of https://github.com/eclipse/xtext/issues/1091

**Closed by cdietrich** 2017-01-13 12:41 UTC

**Comment by cdietrich** [comment] 2017-01-19 15:02
@olenz fix is "live" now
