### ISSUE TITLE
[usability] Selection in new files created by the wizard

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-xtend#43] opened 2016-09-29 02:27 UTC
When an Xtend element is created the selection in the new file spans the newline:

<img width="245" alt="screenshot 31" src="https://cloud.githubusercontent.com/assets/265597/18938953/cb98e1a4-85fc-11e6-84ea-eda56199ea8f.png">

If one would start editing now the line break is deleted.

<img width="247" alt="screenshot 32" src="https://cloud.githubusercontent.com/assets/265597/18938970/e9f882b2-85fc-11e6-964d-890af15c18d6.png">

What is actually desired is that the cursor is placed within the brackets without any selection.

**Comment by cdietrich** [comment] 2016-11-01 10:35
@kthoms i cannot reproduce this with the current impl. do you have any hints how to reproduce?

**Comment by kthoms** [comment] 2016-11-01 12:43
I'll come back to you tomorrow.

Am 01.11.2016 um 11:35 schrieb Christian Dietrich <notifications@github.com>:

**Comment by kthoms** [comment] 2016-11-07 22:23
Checked again. Strangely I cannot observe the issue in my developer workspace either. But it becomes reproducible when starting the runtime environment from the developer workspace, and then the patch fixes the issue. Maybe there is something different in the underlying behavior of the base plugins and a difference between developer IDE and target platform.

Please start a runtime workspace and create an Xtend class. Then you should face the strange selection.

**Comment by cdietrich** [comment] 2017-01-13 15:16
@kthoms i today saw a different behaviour, how the first tab is marked.

<img width="149" alt="bildschirmfoto 2017-01-13 um 16 16 05" src="https://cloud.githubusercontent.com/assets/238736/21934925/a789fb10-d9ab-11e6-9877-f0b5f0ddec87.png">

**Comment by kthoms** [comment] 2017-01-16 13:13
Reproducible on Oxygen target, not on Luna. I'll try to find a solution that works on both.

**Comment by kthoms** [comment] 2017-01-16 15:16
Hmm, to be more precise, it works for me also when setting Oxygen as target. But when I'm Oomphing an Oxygen distro and install Xtend on it, I can see your issue.
The Oxygen target has slightly more recent version of JFace, but I'm not sure if there is anything in there that fixes this.
So in my devenv I can't reproduce it yet, I'll observe that further.

**Comment by cdietrich** [comment] 2017-08-17 08:30
fixed in Xtext 2.13

**Closed by cdietrich** 2017-08-17 08:30 UTC
Labels: enhancement
