### ISSUE TITLE
incompatibility between Xtend/Xtext2.13 and older versions

### ISSUE THREAD

**Issue by afischer211** [eclipse/xtext-xtend#331] opened 2017-12-18 15:37 UTC
Hello,

I'm on writing active annotations with Xtend2.x. For testing I write some JUnit-tests, which prepare some special test-information-provider (instead of the default runtime-information-providers), which are than used inside of the processors and transformers during code-generation. For ensuring of usage for same instances of these providers I use the classic singleton-pattern for the information-provider (static instance-field and static instance()-method, which looks for null-value of instance-field and instantiates the singleton).
The new situation with Xtend/Xtext 2.13 is, that this standard singleton classes are instantiated *two* times. One instance comes from my unittest-method, the other instances comes from instance()-calls inside processor-classes. After code-generation the execution returns to the unittest and sees the singleton-instance from unittest again. Inside the AA-processor or AA-transformer I see the new/second singleton-instance. After some recherche and debugging I learned, that this can occur with different class-loaders loading the same bytecode for the singleton-class.
The same unit-test and the whole concept runs without problems with Xtend/Xtext 2.11. There is only *one* singleton-instance created, the null-check in the static instance()-method works as expected. So I think, the handling with different classloaders is a new feature of Xtend/Xtext2.13 - may be for better isolation of the framework from other libraries or the new LSP-support?

How can I create a object in the unittest and give it on "official way" to the processors and transformers? Can/should I use Guice or is there any "object-registry"? How can I create singletons between unit-test outside of "xtend-context" and share it with the processors/transformers inside of the "xtend-context"?

Kindly regards,
Alexander Fischer

**Comment by cdietrich** [comment] 2017-12-18 16:01
we did some changes in xtext 2.14 as well. did you debug the loading of the processors in JdtBasedProcessorProvider vs ProcessorInstanceForJvmTypeProvider

**Comment by cdietrich** [comment] 2017-12-18 16:08
could you share an example processor and test that were working?

**Comment by afischer211** [comment] 2017-12-18 17:43
Hello,
I have attached a zip-archive with Xtend-sources for a very simple processor, a simple singleton and a simple unittest. With Xtend2.12/Xtext2.12 the singleton is only *one* time instantiated, with Xtend2.13/Xtext2.13 the singleton is instantiated *two* times (one times in unittest, second times in processor with an
[xtend.zip](https://github.com/eclipse/xtext-xtend/files/1568915/xtend.zip)
other address).

**Comment by afischer211** [comment] 2017-12-18 17:45
If the usage of singleton is problematic (I can follow your arguments), how can I inject/transport some informations from unittest-method into the called processor (for instance specific informations for generation of Java-sources)? The usage of a singleton was my first idea for this, the singleton is the shared information-manager.

**Comment by cdietrich** [comment] 2017-12-19 05:51
I am still not sure: is this about unit tests only or is this a runtime issue

**Comment by cdietrich** [comment] 2017-12-19 06:22
cannot reproduce this with your example in a plugin project .....
(tested with xtext 2.14 snapshot)

**Comment by afischer211** [comment] 2017-12-19 08:24
**Currently the problem is a issue on unit-tests.** I have tested it again - the singleton is instantiated first time in the test()-method (checked with Eclipse-debugger). Then the compilerTester is called , which creates and runs the doTransform()-method of the processor. Here the singleton-method instance() is called again and creates a **new** instance! I see this in the debugger, the null-check in the singleton-method returns (unexpected) true.
I run with Xtend/Xtext2.13 inside of an Eclipse-Oxygen IDE (call "debug as junit-test" for the test-class).
With previous version the second call of instance() returns the earlier created instance correctly.

The exactly same code but with other targetplatform (with last version of Xtend/Xtext before 2.13) runs without this problems.

How can I avoid the singleton and give some pre-initialized objects from unittest into the (later by Xtend created) processor?

**Comment by cdietrich** [comment] 2017-12-19 09:20
can you please share a complete project so that i can reproduce the problem.
i am still not sure what you need to share.

**Comment by afischer211** [comment] 2017-12-19 09:57
I will see, if I can create a complete test-project (also with Manifest.MF and so on).
The singleton in real scenario is a manager-class, which provides factories for different purposes. In unit-tests I can register specific factories into the factory-manager, the processor class can later call manager.instance().getFactory() and receives the wished factory (default or specific pre-registered factory from unittest).
The problem is, if the singleton is not a real singleton, the pre-registration of test-factories is not working anymore. The processor will receive a new "empty" manager-instance without pre-registered factories (or only with the defaults).
So I depend on the fact, there is really only **one**instance of the manager-singleton between the unit-test class/method and the later processor-runs.

**Comment by cdietrich** [comment] 2017-12-22 10:26
@afischer211 any news on this?

**Comment by cdietrich** [comment] 2018-01-09 12:43
@afischer211 ping

**Comment by cdietrich** [comment] 2018-01-23 06:59
i will close this since we did not get any feedback

**Closed by cdietrich** 2018-01-23 06:59 UTC
Labels: question
