### ISSUE TITLE
new collection literals break older Xtend compilers

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-xtend#286] opened 2017-10-17 13:44 UTC
In a workspace where I have Xtend IDE 2.11.0 installed in my host Eclipse... 
active annotation processing fails with this exception after I upgraded my target platform to Xtext 2.13.:

```
Error during annotation processing:
java.lang.NoSuchMethodError:
org.eclipse.xtext.xbase.lib.CollectionLiterals.newArrayList()Ljava/util/ArrayList;
at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.getFinalFieldsConstructorArgumentTypes(FinalFieldsConstructorProcessor.java:99)
at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.hasFinalFieldsConstructor(FinalFieldsConstructorProcessor.java:77)
at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.needsFinalFieldConstructor(FinalFieldsConstructorProcessor.java:71)
at org.eclipse.xtend.lib.annotations.AccessorsProcessor._transform(AccessorsProcessor.java:371)
at org.eclipse.xtend.lib.annotations.AccessorsProcessor.transform(AccessorsProcessor.java:391)
at org.eclipse.xtend.lib.annotations.AccessorsProcessor$1.accept(AccessorsProcessor.java:344)
at org.eclipse.xtend.lib.annotations.AccessorsProcessor$1.accept(AccessorsProcessor.java:341)
at java.lang.Iterable.forEach(Iterable.java:75)
at org.eclipse.xtend.lib.annotations.AccessorsProcessor.doTransform(AccessorsProcessor.java:347)
```

**Comment by kthoms** [comment] 2017-10-17 13:47
Did you specify a lower version bound of 2.13 for xbase.lib? All Xtext bundles declare this version constraint now. Or is it somewhere missing?
The release notes contain an appropriate entry about that constraint.

**Comment by cdietrich** [comment] 2017-10-17 13:48
you need xtext 2.13 to run xtext 2.13 projects

**Comment by cdietrich** [comment] 2017-10-17 13:49
the aa class loading bypasses these contraints

**Comment by cdietrich** [comment] 2017-10-17 13:49
and if you have xtext 2.11 in your host eclipse of course nobody will see the contraints

**Comment by cdietrich** [comment] 2017-10-17 13:51
have have the same incompatibilities in general if we use aa between versions

**Comment by kthoms** [comment] 2017-10-17 13:51
So you have a newer target than the IDE that you develop with? Usually not a good idea.

**Comment by meysholdt** [comment] 2017-10-17 13:51
my target platform only contains xbase.lib 2.13. Thus I assume the old xbase.lib came from my host eclipse.

**Comment by cdietrich** [comment] 2017-10-17 13:52
all aa stuff is loaded from host eclipse :(

**Comment by cdietrich** [comment] 2017-10-17 13:54
that's the keypoint about aa. with my latest patch i loosen this contrained to xbase/xtend lib and guava, but still the issue. that was the cause for the compile error miro had with the traced annotation in xtext-core since it was loaded from bootstrap and not from target platform / classpath of model project

**Comment by meysholdt** [comment] 2017-10-17 13:54
apparently `org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor` got pulled from the target platform, otherwise it wouldn't have been linked agains `org.eclipse.xtext.xbase.lib.CollectionLiterals.newArrayList()Ljava/util/ArrayList`

**Comment by cdietrich** [comment] 2017-10-17 13:55
nope. there is the linking on processing and the treatment afterwards

**Comment by cdietrich** [comment] 2017-10-17 13:56
ahh yes in eclipse the behaviour is even more different since it customizes that loading

**Comment by cdietrich** [comment] 2017-10-17 13:57
=> we have this issues since ever with each update what changes xbase lib

**Comment by meysholdt** [comment] 2017-10-17 13:58
I meant when `FinalFieldsConstructorProcessor` got compiled some feature call got resolved to `org.eclipse.xtext.xbase.lib.CollectionLiterals.newArrayList()Ljava/util/ArrayList`. Thus, when `FinalFieldsConstructorProcessor` got compiled the xbase.lib 2.13 was present. Thus, `FinalFieldsConstructorProcessor` must be from 2.13.

**Comment by cdietrich** [comment] 2017-10-17 13:59
yes but where does it pick the lib from?

**Comment by cdietrich** [comment] 2017-10-17 14:00
protected def getParentClassLoader() {
		val bundleClassLoader = TransformationContext.classLoader
		return bundleClassLoader
	}

=> this should use the installed code from host eclipse

**Comment by cdietrich** [comment] 2017-10-17 14:03
=> what is installed in your host eclipse?

**Comment by cdietrich** [comment] 2017-10-17 15:37
@meysholdt i could not reproduce this
=> are you sure no xtext 2.13 stuff smuggeled into dev eclipse?

**Comment by cdietrich** [comment] 2017-10-17 16:14
hmmm

`java.lang.ClassNotFoundException: org.eclipse.xtend.lib.annotations.AccessorsProcessor cannot be found by org.eclipse.xtend.lib.macro_2.12.0.v20170518-0757
	`

**Comment by cdietrich** [comment] 2017-10-17 16:16
but
`
bundleClassLoader.loadClass("org.eclipse.xtext.xbase.lib.CollectionLiterals")
	 (java.lang.Class<T>) class org.eclipse.xtext.xbase.lib.CollectionLiterals`

**Comment by cdietrich** [comment] 2017-10-17 16:19
=> the processor is not load from host but the lib is.
=> it will explode if versions dont match.
=> but why cant transformation context see the processor? => cause macro has dependency to xbase lib but not to xtend.lib

**Comment by cdietrich** [comment] 2017-10-17 16:21
=> i dont see how this can be solved as long as we need to load the processor api and xbase lib from the host eclipse

**Comment by cdietrich** [comment] 2017-10-18 11:52
cc @svenefftinge

**Comment by szarnekow** [comment] 2017-10-18 12:01
We have to load the processor API and its dependencies in the host eclipse because the compiler is linked to these. Otherwise we would get incompatible class versions. In that regard, the AA are not forward compatible when Xbase lib is changed and new processor versions in the TP and the compiler are not in sync.

**Comment by svenefftinge** [comment] 2017-10-18 14:28
Sorry, I missed this ticket. It's like Sebastian says: The class files of the annotation processor are compiled against what is on the project's classpath (2.13) and then loaded in the IDE and executed against the installed xbase lib. 
So we run into this, whenever an active annotation uses new elements from xbase lib that are not available in the Eclipse installation yet. I don't think we can do anything about it other than telling people to upgrade their Eclipse.

**Comment by cdietrich** [comment] 2017-10-18 14:45
=> will close this issue

**Closed by cdietrich** 2017-10-18 14:45 UTC
Labels: confirmed, wontfix
