### ISSUE TITLE
Strange compilation failures ("missing type Object")

### ISSUE THREAD

**Issue by sigiesec** [eclipse/xtext-xtend#576] opened 2018-09-17 11:25 UTC
When compiling some code with the xtend-maven-plugin:2.13.0, I get strange errors such as:
```
ERROR: 	Bar.xtend - /mnt/jenkins/ws/.../Bar.xtend
49: The method ... from the type Bar refers to the missing type Object
```

What makes this really strange is that "Object" is reported to be missing. 

Interestingly, this seems to depend on the environment. The same code compiles fine in my local eclipse, and in another CI environment with the same plugin version.

Unfortunately, I was not able to pin this down to a minimal example. 

Maybe someone has an idea what might go wrong here?

**Comment by cdietrich** [comment] 2018-09-17 11:27
Could be a unknown jdk used.

**Comment by tivervac** [comment] 2018-09-17 11:27
Usually you get this error when you can't access the return type of a method call. Try finding the method that raises the error, find out it's return type. Now add this return type's plugin to your manifest.mf file

**Comment by sigiesec** [comment] 2018-09-17 12:30
@tivervac I can't imagine this is the problem here, since this builds fine with the same POMs in another environment. 

@cdietrich What do you mean by "unknown JDK"? Which ones are known (by what?)? The version used appears to be jdk1.8.0_144

FYI, the same problem exists with xtend-maven-plugin 2.14.0

**Comment by cdietrich** [comment] 2018-09-17 12:34
No. Nothing to reproduce. No idea. Did you try to debug into the code ?

**Comment by sigiesec** [comment] 2018-09-17 13:07
I managed to change this to use a more recent JDK (i.e. jdk1.8.0_181), however the problem stays the same.

What do you mean by "debug into the code"? Which code? Of the xtend-maven-plugin? I cannot do this easily, as this only fails on some Jenkins node. Locally it works, both from within Eclipse, and also using maven.

**Comment by cdietrich** [comment] 2018-09-17 13:09
Did you tpcheck the classpath twice? Are you sure some classes on the way between your and the ones used are not missing ?

**Comment by sigiesec** [comment] 2018-09-17 14:37
I am pretty sure, yes. As I said, the project builds fine here, e.g.: https://travis-ci.org/btc-ag/service-idl/builds/429590431

Do you know where does this error message comes from? I cannot find any mention of it in the xtend-xtext code.

**Comment by sigiesec** [comment] 2018-09-17 16:48
After integrating the changes into another branch, it works. Still strange, since I had already copied the branch, to exclude the possibility that it was somehow related to the name of the branch, its length etc.

Regardless of what the underlying problem is, the error message is very confusing. But I understand that without identifying the root cause, it is hard to improve anything.

So probably this issue can be closed for now, if I reencounter the problem, and find out something more on the cause, I will reopen it.

**Comment by cdietrich** [comment] 2018-09-17 16:49
Can you build with debug mode? To get a complete stacktrace

**Comment by sigiesec** [comment] 2018-09-17 16:56
Is this the stacktrace you meant?

```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.13.0:compile (default) on project com.btc.serviceidl: Error compiling xtend sources in '/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src:/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src-gen'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.13.0:compile (default) on project com.btc.serviceidl: Error compiling xtend sources in '/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src:/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src-gen'.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error compiling xtend sources in '/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src:/mnt/jenkins/ws/cab/btc-ag-github/service-idl/adapt-futureutil/ws/com.btc.serviceidl/src-gen'.
	at org.eclipse.xtend.maven.AbstractXtendCompilerMojo.compile(AbstractXtendCompilerMojo.java:176)
	at org.eclipse.xtend.maven.XtendCompile.internalExecute(XtendCompile.java:62)
	at org.eclipse.xtend.maven.AbstractXtendMojo.execute(AbstractXtendMojo.java:39)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

**Comment by cdietrich** [comment] 2018-09-17 16:59
That won’t help. Error comes from here
https://github.com/eclipse/xtext-extras/blob/96c24736d369b2fa3c055779a69f9fbac0b5d6c9/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseValidator.java

**Comment by sigiesec** [comment] 2018-09-17 17:13
Hm, there is no reference to XbaseValidator in the build log. What debug mode are you referring to? I ran maven with -X -e to get this stacktrace. Is there anything else that should be set?

**Comment by cdietrich** [comment] 2018-09-17 17:15
Since it’s a validator so no chance without reproducing and debugging locally

**Comment by kthoms** [comment] 2018-09-21 15:10
@sigiesec A customer reported a similar issue. It occurs for them in conjunction of trying to upgrade to Java 10 in their build. But you observed that on Java 8. Are there any Active Annotations involved in the scenario?

**Comment by sigiesec** [comment] 2018-10-01 13:51
@kthoms Sorry I only get back to this now, I somehow missed your question. The problem just reappeared. 

Yes, Active Annotations (in particular `@Accessors`) are widely used in our Xtend code. 

Actually, I am not 100% sure if this really runs with Java8. The system is configured to use Java8, but maybe there are some ambiguities in the environment. Do you know how I could check for sure what JVM version is used during compilation with the xtend-maven-plugin?

**Comment by kthoms** [comment] 2018-10-01 21:43
The xtend-maven-plugin uses JDT under the hood, the JVM is the one from the Maven process. Our customer resolved his issue with the patch https://github.com/eclipse/xtext-xtend/pull/585. Actually it wasn't the Active Annotations which turned out to make the trouble, but more that they use Maven Toolchains (and Java 10). So I am not sure that you have the same trouble, but 'missing type Object' could be also Toolchain related.

**Comment by cdietrich** [comment] 2018-11-05 14:21
still have no clue what we should do with that issue besides closing it was wontfix

**Comment by sigiesec** [comment] 2019-03-05 16:39
I am having the same problem again. Any chance that the XbaseValidator is amended by a debugging/tracing mode that allows to analyze the problem better?

**Comment by cdietrich** [comment] 2019-03-24 10:51
@sigiesec i still wonder if you could share a sample project reproducing this.
please note: this problem might be happen if you use Xtext < 2.17 with Java Target 8 but used JDK/JRE = 11

**Comment by sigiesec** [comment] 2019-03-24 18:11
I can try to but the conditions under which this happens appear to be very special. It happens on our CI nodes, but not on my local machine, and only with specific branches, with no peculiar changes compared to others that work.

**Comment by cdietrich** [comment] 2019-03-24 18:12
Another thing could be having strange versions of asm on classpath

**Comment by cdietrich** [comment] 2019-05-06 07:05
@sigiesec i still cannot reproduce this.
=> i intend to close this issue

**Comment by sigiesec** [comment] 2019-05-06 07:13
@cdietrich Sorry that I can't provide something to reproduce this. Still, unfortunately this is blocking us again. 

I am ok with closing this issue for now, but please open another issue to extend the diagnostic output, so that there is a chance to identify the cause of the problem. "missing type Object" is very brief, it does not even include the FQN. Are there other properties that might lead to an existing type (java.lang.Object obviously exists) to be consider non-matching? Then these properties should be included in the message.

**Comment by cdietrich** [comment] 2019-05-06 07:14
did you check the classpath for bad asm versions then?

**Comment by sigiesec** [comment] 2019-05-06 07:20
Sorry, I missed that comment, I will check that. What would be a strange version, which version should be used?

**Comment by cdietrich** [comment] 2019-05-06 07:21
i dont know which version it was with your old xtext version.
asm <= 6.x is bad for sure

**Comment by sigiesec** [comment] 2019-05-16 12:14
At the moment this is Xtext 2.16.0, and the version of org.objectweb.asm is 7.0.0, so this doesn't look too bad.

I can try to update to the current Xtext version and see what happens then.

The full classpath (I stripped the base directory) is:
{code}
[DEBUG] Set classpath: /tmp/.m2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtext/2.16.0.v20181203-0514/org.eclipse.xtext-2.16.0.v20181203-0514.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtext.xbase/2.16.0.v20181203-0528/org.eclipse.xtext.xbase-2.16.0.v20181203-0528.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.equinox.common/3.10.200.v20181021-1645/org.eclipse.equinox.common-3.10.200.v20181021-1645.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.ecore/2.16.0.v20181124-0637/org.eclipse.emf.ecore-2.16.0.v20181124-0637.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtext.xbase.lib/2.16.0.v20181203-0507/org.eclipse.xtext.xbase.lib-2.16.0.v20181203-0507.jar:/tmp/.m2/p2/osgi/bundle/org.antlr.runtime/3.2.0.v201101311130/org.antlr.runtime-3.2.0.v201101311130.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtext.util/2.16.0.v20181203-0514/org.eclipse.xtext.util-2.16.0.v20181203-0514.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.common/2.15.0.v20180914-1817/org.eclipse.emf.common-2.15.0.v20180914-1817.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtend.lib/2.16.0.v20181203-0507/org.eclipse.xtend.lib-2.16.0.v20181203-0507.jar:/tmp/.m2/p2/osgi/bundle/com.google.guava/21.0.0.v20170206-1425/com.google.guava-21.0.0.v20170206-1425.jar:/tmp/.m2/p2/osgi/bundle/org.apache.log4j/1.2.15.v201012070815/org.apache.log4j-1.2.15.v201012070815.jar:/tmp/.m2/p2/osgi/bundle/com.google.inject/3.0.0.v201312141243/com.google.inject-3.0.0.v201312141243.jar:/tmp/.m2/p2/osgi/bundle/javax.inject/1.0.0.v20091030/javax.inject-1.0.0.v20091030.jar:/tmp/.m2/p2/osgi/bundle/com.ibm.icu/63.1.0.v20181030-1705/com.ibm.icu-63.1.0.v20181030-1705.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.osgi/3.13.200.v20181130-2106/org.eclipse.osgi-3.13.200.v20181130-2106.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-antlr.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-bcel.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-bsf.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-log4j.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-oro.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-regexp.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-resolver.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-apache-xalan2.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-commons-logging.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-commons-net.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-jai.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-javamail.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-jdepend.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-jmf.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-jsch.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-junit.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-junit4.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-junitlauncher.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-launcher.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-netrexx.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-swing.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-testutil.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant-xz.jar:/tmp/.m2/.cache/tycho/org.apache.ant-1.10.5.v20180808-0324.jar/lib/ant.jar:/tmp/.m2/p2/osgi/bundle/org.apache.commons.cli/1.2.0.v201404270220/org.apache.commons.cli-1.2.0.v201404270220.jar:/tmp/.m2/p2/osgi/bundle/org.apache.commons.lang/2.6.0.v201404270220/org.apache.commons.lang-2.6.0.v201404270220.jar:/tmp/.m2/p2/osgi/bundle/org.apache.commons.logging/1.2.0.v20180409-1502/org.apache.commons.logging-1.2.0.v20180409-1502.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.commands/3.9.200.v20180827-1727/org.eclipse.core.commands-3.9.200.v20180827-1727.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.contenttype/3.7.200.v20181107-1343/org.eclipse.core.contenttype-3.7.200.v20181107-1343.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.equinox.preferences/3.7.200.v20180827-1235/org.eclipse.equinox.preferences-3.7.200.v20180827-1235.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.equinox.registry/3.8.200.v20181008-1820/org.eclipse.equinox.registry-3.8.200.v20181008-1820.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.expressions/3.6.200.v20180817-1401/org.eclipse.core.expressions-3.6.200.v20180817-1401.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.runtime/3.15.100.v20181107-1343/org.eclipse.core.runtime-3.15.100.v20181107-1343.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.filesystem/1.7.200.v20180828-0158/org.eclipse.core.filesystem-1.7.200.v20180828-0158.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.jobs/3.10.200.v20180912-1356/org.eclipse.core.jobs-3.10.200.v20180912-1356.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.resources/3.13.200.v20181121-1020/org.eclipse.core.resources-3.13.200.v20181121-1020.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.equinox.app/1.4.0.v20181009-1752/org.eclipse.equinox.app-1.4.0.v20181009-1752.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.core.variables/3.4.300.v20181028-0627/org.eclipse.core.variables-3.4.300.v20181028-0627.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.debug.core/3.13.100.v20181201-1650/org.eclipse.debug.core-3.13.100.v20181201-1650.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.codegen/2.15.0.v20181120-2156/org.eclipse.emf.codegen-2.15.0.v20181120-2156.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.jdt.core/3.16.0.v20181130-1748/org.eclipse.jdt.core-3.16.0.v20181130-1748.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.jdt.launching/3.12.0.v20181119-1621/org.eclipse.jdt.launching-3.12.0.v20181119-1621.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.text/3.8.0.v20180923-1636/org.eclipse.text-3.8.0.v20180923-1636.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.codegen.ecore/2.16.0.v20181206-1055/org.eclipse.emf.codegen.ecore-2.16.0.v20181206-1055.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.ecore.xmi/2.15.0.v20180706-1146/org.eclipse.emf.ecore.xmi-2.15.0.v20180706-1146.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.mwe.core/1.3.21.201705291011/org.eclipse.emf.mwe.core-1.3.21.201705291011.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.mwe2.runtime/2.9.1.201705291011/org.eclipse.emf.mwe2.runtime-2.9.1.201705291011.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.mwe.utils/1.3.21.201705291011/org.eclipse.emf.mwe.utils-1.3.21.201705291011.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.emf.mwe2.lib/2.9.1.201705291011/org.eclipse.emf.mwe2.lib-2.9.1.201705291011.jar:/tmp/.m2/.cache/tycho/org.eclipse.jdt.debug-3.12.100.v20181116-1959.jar/jdi.jar:/tmp/.m2/.cache/tycho/org.eclipse.jdt.debug-3.12.100.v20181116-1959.jar/jdimodel.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtend.lib.macro/2.16.0.v20181203-0507/org.eclipse.xtend.lib.macro-2.16.0.v20181203-0507.jar:/tmp/.m2/p2/osgi/bundle/org.eclipse.xtext.common.types/2.16.0.v20181203-0528/org.eclipse.xtext.common.types-2.16.0.v20181203-0528.jar:/tmp/.m2/p2/osgi/bundle/org.objectweb.asm/7.0.0.v20181030-2244/org.objectweb.asm-7.0.0.v20181030-2244.jar
{code}

**Comment by cdietrich** [comment] 2019-05-16 12:22
i still wonder how to get a reproducing sample

**Comment by sigiesec** [comment] 2019-05-21 11:36
I have updated the node to use JDK 11.0.3 now, but the problem persists.

**Comment by szarnekow** [comment] 2019-05-21 11:48
> I have updated the node to use JDK 11.0.3 now, but the problem persists.

That was tested with Xtext 2.17.1 ?

**Comment by DanySK** [comment] 2019-05-21 23:17
I believe I got a reproducible failure. Happens only with JDK 11 and MacOS. Tested with Xtext 2.16.0.
[Travis Build](https://travis-ci.org/Protelis/Protelis-Parser/jobs/535525531)
[Archived raw log](http://archive.fo/Q9n3y)

note: upon failure, I relaunch with flags for verbosity.

**Comment by cdietrich** [comment] 2019-05-22 04:23
Well for complete support of 11 version 2.16.0 is not sufficient => what happen with 2.17.1

**Comment by johanwannheden** [comment] 2019-11-09 00:08
I can reproduce this problem with Xtext version 2.19.0 running from a Maven process with Java 8. The Maven build setup resembles the one from the `maven-xtext-example` project.

**Comment by cdietrich** [comment] 2019-11-09 08:07
i still wonder if you could package that to a reproducible example
i also wonder what happens if you run this with a a clean maven repo (`-Dmaven.repo.local`)
also note there are bugs in maven 3.6.1. and 3.6.2 with tycho.
thus also make sure you use maven 3.6.0

**Comment by johanwannheden** [comment] 2019-11-09 15:27
Thanks for the quick reply and the hint regarding bugs with Maven 3.6+ and Tycho!

Yes, the problem persists when using Maven 3.6.0 and also with the local repo option.

A reproducer is [this repository](https://github.com/johanwannheden/xtext-xtend-576-reproducer/tree/master/com.mimacom.ddd.dm.base). Please note the following:
* I'm in the process of "Mavenizing" the projects, previously these were plain Eclipse/P2 projects and I'm not done yet (some projects are not yet referenced by the root pom and have no pom.xml)
* there is a "base" model project containing an Ecore model (`com.mimacom.ddd.dm.base`); this builds fine
* then there is a family of projects for an Xtext DSL (DMX): it's the following project which fails to build: `com.mimacom.ddd.dm.dmx`

**Comment by cdietrich** [comment] 2019-11-09 15:37
i can confirm that the sample repo fails to build

**Comment by johanwannheden** [comment] 2019-11-09 15:45
Not when triggering the MWE2 Workflow from within Eclipse though..

**Comment by cdietrich** [comment] 2019-11-09 15:47
i have compile errors in eclipse too.
the metamodel for dmx is not generated

**Comment by cdietrich** [comment] 2019-11-09 15:53
when adding the missing ecoregenerator (to the end of the workflow)
it works fine

```
	
	component = org.eclipse.emf.mwe2.ecore.EcoreGenerator {
		genModel = "${genModel}"
       srcPath = "${rootPath}/${project}/src"
	}
```

**Comment by cdietrich** [comment] 2019-11-09 15:54
=> seems a different issue / follow up error in your case

**Comment by johanwannheden** [comment] 2019-11-09 16:00
Sorry, I must have got something messed up when creating the reproducer. The initial problem I had tough, was manifested by the "refers to the missing type Object" message.. will get back when this is the case. Thanks anyway.

**Comment by cdietrich** [comment] 2019-11-09 16:08
yes it is also part of the messages in the reproducer

```
ERROR: 	DmxTypeCheckingValidator.xtend - /home/dietrich/tmp/xtext-xtend-576-reproducer/com.mimacom.ddd.dm.dmx/src/com/mimacom/ddd/dm/dmx/validation/DmxTypeCheckingValidator.xtend
57: The field DmxTypeCheckingValidator.DMX refers to the missing type Object
```

**Comment by johanwannheden** [comment] 2019-11-13 10:53
I don't suppose there's any news on this?

**Comment by cdietrich** [comment] 2019-11-13 11:12
@johanwannheden  do you have anything that reproduces the issue?

**Comment by johanwannheden** [comment] 2019-11-13 13:57
Unfortunately not: there is something fishy going on which I don't understand. Whenever I try to update the reproducer (based on the real world project), the error does not manifest itself. Can you extract anything useful from [this installation log](https://github.com/johanwannheden/xtext-xtend-576-reproducer/blob/master/install.log) produced by Maven? Sorry for the not so useful help in tackling this issue, hopefully I'll soon get some more insight myself and provide you with more information.

**Comment by johanwannheden** [comment] 2019-11-13 14:30
As a matter of fact, deleting the Maven repo (or using a local one) now works. Cannot reproduce error.

**Comment by szarnekow** [comment] 2019-11-19 10:43
Hmm that's a pity. Closing for now, but please feel free to reopen if the problem occurs again.

**Closed by szarnekow** 2019-11-19 10:43 UTC
