### ISSUE TITLE
StackOverflowError in Xtend editor

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-xtend#158] opened 2017-02-21 08:51 UTC
Here is a reproducible example:

```

class TestClazz {
    static val FORMS = #{
        Form1 -> "",
        Form2 -> ""
    }
}

class Form1 extends AbstractForm<P1> implements View1 {
}

class Form2 extends AbstractForm<P2> implements View2 {
}

abstract class AbstractForm<P> {
}

interface View1 extends View<P1> {
}

interface View2 extends View<P2> {
}

interface View<P> {
}

abstract class AbstractP<V> {
}

class P1 extends AbstractP<View1> {
}

class P2 extends AbstractP<View2> {
}

```

```
An internal error occurred during: "Xtext validation".

java.lang.StackOverflowError
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl.eClass(MinimalEObjectImpl.java:688)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.getSuperType(ParameterizedTypeReference.java:734)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.getSuperType(ParameterizedTypeReference.java:742)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.getSuperType(ParameterizedTypeReference.java:742)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.getSuperType(ParameterizedTypeReference.java:742)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.internalGetSuperType(ParameterizedTypeReference.java:698)
	at org.eclipse.xtext.xbase.typesystem.references.ParameterizedTypeReference.getSuperType(ParameterizedTypeReference.java:618)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getSuperType(TypeConformanceComputer.java:111)
	at org.eclipse.xtext.xbase.typesystem.conformance.RawTypeConformanceComputer.doIsConformant(RawTypeConformanceComputer.java:905)
	at org.eclipse.xtext.xbase.typesystem.conformance.RawTypeConformanceComputer.doIsConformant(RawTypeConformanceComputer.java:319)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.isConformant(TypeConformanceComputer.java:102)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.conformsToAll(TypeConformanceComputer.java:693)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonSuperType(TypeConformanceComputer.java:234)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonParameterSuperType(TypeConformanceComputer.java:598)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.enhanceSuperType(TypeConformanceComputer.java:535)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getTypeParametersForSupertype(TypeConformanceComputer.java:467)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonSuperType(TypeConformanceComputer.java:290)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonParameterSuperType(TypeConformanceComputer.java:598)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.enhanceSuperType(TypeConformanceComputer.java:535)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getTypeParametersForSupertype(TypeConformanceComputer.java:467)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonSuperType(TypeConformanceComputer.java:290)
	at org.eclipse.xtext.xbase.typesystem.conformance.TypeConformanceComputer.getCommonParameterSuperType(TypeConformanceComputer.java:598)
	at 

```

**Comment by cdietrich** [comment] 2017-02-21 09:34
@dhuebner which java minor version do you use?

**Comment by cdietrich** [comment] 2017-03-24 19:36
might be duplicate of https://bugs.eclipse.org/bugs/show_bug.cgi?id=495314

**Comment by cdietrich** [comment] 2018-04-03 11:52
@szarnekow is this fixed along with the other issues?

**Comment by szarnekow** [comment] 2018-04-03 11:54
Yes, I was just looking for this ticket :)

**Comment by szarnekow** [comment] 2018-04-03 11:54
Resolved in xtext-extras

**Closed** 2018-04-03 11:54 UTC
Labels: bug, confirmed
